export type NerisSectionId =
  | "core"
  | "narrative"
  | "location"
  | "incidentTimes"
  | "resources"
  | "emergingHazards"
  | "hazards"
  | "fire"
  | "exposures"
  | "riskReduction"
  | "medical"
  | "rescuesCasualties"
  | "attachments";

export type NerisFieldInputKind =
  | "text"
  | "date"
  | "time"
  | "datetime"
  | "textarea"
  | "select"
  | "multiselect"
  | "readonly";

export interface NerisSectionConfig {
  id: NerisSectionId;
  label: string;
  helper: string;
}

export interface NerisValueOption {
  value: string;
  label: string;
}

export interface NerisConditionalRule {
  fieldId: string;
  operator: "equals" | "notEmpty" | "isEmpty" | "includes";
  value?: string;
}

export interface NerisFieldMetadata {
  id: string;
  sectionId: NerisSectionId;
  label: string;
  inputKind: NerisFieldInputKind;
  required?: boolean;
  requiredIf?: NerisConditionalRule;
  optionsKey?: keyof typeof NERIS_VALUE_SETS;
  placeholder?: string;
  helperText?: string;
  maxLength?: number;
  rows?: number;
  layout?: "half" | "full";
}

export type NerisFormValues = Record<string, string>;

export interface NerisValidationResult {
  isValid: boolean;
  errors: Record<string, string>;
}

interface CreateNerisDefaultsInput {
  callNumber: string;
  incidentType?: string;
  receivedAt?: string;
  address?: string;
}

export const NERIS_METADATA_VERSION = "NERIS v1 metadata scaffold";

export const NERIS_SCHEMA_REFERENCE_LINKS = [
  "https://neris.fsri.org/technical-reference",
  "https://api.neris.fsri.org/v1/openapi.json",
  "https://neris-prod-public.s3.us-east-2.amazonaws.com/docs/NERIS_V1_Core_Schemas.zip",
  "https://neris-prod-public.s3.us-east-2.amazonaws.com/docs/NERIS_V1_Secondary_Schemas.zip",
] as const;

export const NERIS_FORM_SECTIONS: NerisSectionConfig[] = [
  {
    id: "core",
    label: "Core",
    helper:
      "Complete baseline NERIS incident fields. Required and conditional rules are metadata-driven.",
  },
  {
    id: "narrative",
    label: "Narrative",
    helper: "",
  },
  {
    id: "location",
    label: "Location",
    helper: "",
  },
  {
    id: "incidentTimes",
    label: "Incident Times",
    helper: "Track lifecycle timestamps from dispatch through clearance.",
  },
  {
    id: "resources",
    label: "Resources",
    helper: "Record units, apparatus, and mutual aid resource usage.",
  },
  {
    id: "emergingHazards",
    label: "Emerging Hazards",
    helper: "Flag hazardous materials or hazards found on scene.",
  },
  {
    id: "hazards",
    label: "Hazards",
    helper: "Capture chemical and hazardous material incident details.",
  },
  {
    id: "fire",
    label: "Fire",
    helper:
      "Capture fire-specific investigation and suppression details from the NERIS payload.",
  },
  {
    id: "exposures",
    label: "Exposures",
    helper: "Document threatened structures, vehicles, or adjacent risk.",
  },
  {
    id: "riskReduction",
    label: "Risk Reduction",
    helper: "Capture prevention/education actions connected to this incident.",
  },
  {
    id: "medical",
    label: "Medical",
    helper: "Document patient care and related medical observations.",
  },
  {
    id: "rescuesCasualties",
    label: "Rescues/Casualties",
    helper: "Track rescues, injuries, and casualty outcomes.",
  },
  {
    id: "attachments",
    label: "Attachments",
    helper: "Attach CAD notes, photos, diagrams, and supporting files.",
  },
];

const NERIS_INCIDENT_TYPE_VALUES: readonly string[] = [
  "FIRE: OUTSIDE_FIRE: CONSTRUCTION_WASTE",
  "FIRE: OUTSIDE_FIRE: OTHER_OUTSIDE_FIRE",
  "FIRE: OUTSIDE_FIRE: OUTSIDE_TANK_FIRE",
  "FIRE: OUTSIDE_FIRE: TRASH_RUBBISH_FIRE",
  "FIRE: OUTSIDE_FIRE: VEGETATION_GRASS_FIRE",
  "FIRE: OUTSIDE_FIRE: WILDFIRE_WILDLAND",
  "FIRE: OUTSIDE_FIRE: WILDFIRE_URBAN_INTERFACE",
  "FIRE: OUTSIDE_FIRE: UTILITY_INFRASTRUCTURE_FIRE",
  "FIRE: OUTSIDE_FIRE: DUMPSTER_OUTDOOR_CONTAINER_FIRE",
  "FIRE: SPECIAL_FIRE: ESS_FIRE",
  "FIRE: SPECIAL_FIRE: EXPLOSION",
  "FIRE: SPECIAL_FIRE: INFRASTRUCTURE_FIRE",
  "FIRE: STRUCTURE_FIRE: STRUCTURAL_INVOLVEMENT_FIRE",
  "FIRE: STRUCTURE_FIRE: ROOM_AND_CONTENTS_FIRE",
  "FIRE: STRUCTURE_FIRE: CONFINED_COOKING_APPLIANCE_FIRE",
  "FIRE: STRUCTURE_FIRE: CHIMNEY_FIRE",
  "FIRE: TRANSPORTATION_FIRE: AIRCRAFT_FIRE",
  "FIRE: TRANSPORTATION_FIRE: VEHICLE_FIRE_PASSENGER",
  "FIRE: TRANSPORTATION_FIRE: VEHICLE_FIRE_COMMERCIAL",
  "FIRE: TRANSPORTATION_FIRE: VEHICLE_FIRE_RV",
  "FIRE: TRANSPORTATION_FIRE: VEHICLE_FIRE_FOOD_TRUCK",
  "FIRE: TRANSPORTATION_FIRE: BOAT_PERSONAL_WATERCRAFT_BARGE_FIRE",
  "FIRE: TRANSPORTATION_FIRE: POWERED_MOBILITY_DEVICE_FIRE",
  "FIRE: TRANSPORTATION_FIRE: TRAIN_RAIL_FIRE",
  "HAZSIT: HAZARD_NONCHEM: BOMB_THREAT_RESPONSE_SUSPICIOUS_PACKAGE",
  "HAZSIT: HAZARD_NONCHEM: ELEC_POWER_LINE_DOWN_ARCHING_MALFUNC",
  "HAZSIT: HAZARD_NONCHEM: ELEC_HAZARD_SHORT_CIRCUIT",
  "HAZSIT: HAZARD_NONCHEM: MOTOR_VEHICLE_COLLISION",
  "HAZSIT: HAZARDOUS_MATERIALS: FUEL_SPILL_ODOR",
  "HAZSIT: HAZARDOUS_MATERIALS: GAS_LEAK_ODOR",
  "HAZSIT: HAZARDOUS_MATERIALS: CARBON_MONOXIDE_RELEASE",
  "HAZSIT: HAZARDOUS_MATERIALS: BIOLOGICAL_RELEASE_INCIDENT",
  "HAZSIT: HAZARDOUS_MATERIALS: RADIOACTIVE_RELEASE_INCIDENT",
  "HAZSIT: HAZARDOUS_MATERIALS: HAZMAT_RELEASE_TRANSPORT",
  "HAZSIT: HAZARDOUS_MATERIALS: HAZMAT_RELEASE_FACILITY",
  "HAZSIT: OVERPRESSURE: RUPTURE_WITHOUT_FIRE",
  "HAZSIT: OVERPRESSURE: NO_RUPTURE",
  "HAZSIT: INVESTIGATION: ODOR",
  "HAZSIT: INVESTIGATION: SMOKE_INVESTIGATION",
  "MEDICAL: ILLNESS: ABDOMINAL_PAIN",
  "MEDICAL: ILLNESS: ALLERGIC_REACTION_STINGS",
  "MEDICAL: ILLNESS: BACK_PAIN_NON_TRAUMA",
  "MEDICAL: ILLNESS: BREATHING_PROBLEMS",
  "MEDICAL: ILLNESS: CARDIAC_ARREST",
  "MEDICAL: ILLNESS: CHEST_PAIN_NON_TRAUMA",
  "MEDICAL: ILLNESS: CONVULSIONS_SEIZURES",
  "MEDICAL: ILLNESS: DIABETIC_PROBLEMS",
  "MEDICAL: ILLNESS: HEADACHE",
  "MEDICAL: ILLNESS: HEART_PROBLEMS",
  "MEDICAL: ILLNESS: OVERDOSE",
  "MEDICAL: ILLNESS: PANDEMIC_EPIDEMIC_OUTBREAK",
  "MEDICAL: ILLNESS: PREGNANCY_CHILDBIRTH",
  "MEDICAL: ILLNESS: PSYCHOLOGICAL_BEHAVIOR_ISSUES",
  "MEDICAL: ILLNESS: SICK_CASE",
  "MEDICAL: ILLNESS: STROKE_CVA",
  "MEDICAL: ILLNESS: UNCONSCIOUS_VICTIM",
  "MEDICAL: ILLNESS: WELL_PERSON_CHECK",
  "MEDICAL: ILLNESS: ALTERED_MENTAL_STATUS",
  "MEDICAL: ILLNESS: NAUSEA_VOMITING",
  "MEDICAL: ILLNESS: UNKNOWN_PROBLEM",
  "MEDICAL: ILLNESS: NO_APPROPRIATE_CHOICE",
  "MEDICAL: INJURY: ANIMAL_BITES",
  "MEDICAL: INJURY: ASSAULT",
  "MEDICAL: INJURY: BURNS_EXPLOSION",
  "MEDICAL: INJURY: CARBON_MONOXIDE_OTHER_INHALATION_INJURY",
  "MEDICAL: INJURY: CHOKING",
  "MEDICAL: INJURY: DROWNING_DIVING_SCUBA_ACCIDENT",
  "MEDICAL: INJURY: ELECTROCUTION",
  "MEDICAL: INJURY: EYE_TRAUMA",
  "MEDICAL: INJURY: FALL",
  "MEDICAL: INJURY: HEAT_COLD_EXPOSURE",
  "MEDICAL: INJURY: MOTOR_VEHICLE_COLLISION",
  "MEDICAL: INJURY: INDUSTRIAL_INACCESSIBLE_ENTRAPMENT",
  "MEDICAL: INJURY: POISONING",
  "MEDICAL: INJURY: GUNSHOT_WOUND",
  "MEDICAL: INJURY: HEMORRHAGE_LACERATION",
  "MEDICAL: INJURY: STAB_PENETRATING_TRAUMA",
  "MEDICAL: INJURY: OTHER_TRAUMATIC_INJURY",
  "MEDICAL: OTHER: HEALTHCARE_PROFESSIONAL_ADMISSION",
  "MEDICAL: OTHER: MEDICAL_ALARM",
  "MEDICAL: OTHER: STANDBY_REQUEST",
  "MEDICAL: OTHER: TRANSFER_INTERFACILITY",
  "MEDICAL: OTHER: AIRMEDICAL_TRANSPORT",
  "MEDICAL: OTHER: INTERCEPT_OTHER_UNIT",
  "MEDICAL: OTHER: COMMUNITY_PUBLIC_HEALTH",
  "PUBSERV: CITIZEN_ASSIST: LOST_PERSON",
  "PUBSERV: CITIZEN_ASSIST: PERSON_IN_DISTRESS",
  "PUBSERV: CITIZEN_ASSIST: CITIZEN_ASSIST_SERVICE_CALL",
  "PUBSERV: CITIZEN_ASSIST: LIFT_ASSIST",
  "PUBSERV: ALARMS_NONMED: FIRE_ALARM",
  "PUBSERV: ALARMS_NONMED: GAS_ALARM",
  "PUBSERV: ALARMS_NONMED: CO_ALARM",
  "PUBSERV: ALARMS_NONMED: OTHER_ALARM",
  "PUBSERV: DISASTER_WEATHER: DAMAGE_ASSESSMENT",
  "PUBSERV: DISASTER_WEATHER: WEATHER_RESPONSE",
  "PUBSERV: OTHER: MOVE_UP",
  "PUBSERV: OTHER: STANDBY",
  "PUBSERV: OTHER: DAMAGED_HYDRANT",
  "RESCUE: OUTSIDE: BACKCOUNTRY_RESCUE",
  "RESCUE: OUTSIDE: CONFINED_SPACE_RESCUE",
  "RESCUE: OUTSIDE: TRENCH",
  "RESCUE: OUTSIDE: EXTRICATION_ENTRAPPED",
  "RESCUE: OUTSIDE: HIGH_ANGLE_RESCUE",
  "RESCUE: OUTSIDE: LOW_ANGLE_RESCUE",
  "RESCUE: OUTSIDE: STEEP_ANGLE_RESCUE",
  "RESCUE: OUTSIDE: LIMITED_NO_ACCESS",
  "RESCUE: STRUCTURE: BUILDING_STRUCTURE_COLLAPSE",
  "RESCUE: STRUCTURE: CONFINED_SPACE_RESCUE",
  "RESCUE: STRUCTURE: ELEVATOR_ESCALATOR_RESCUE",
  "RESCUE: STRUCTURE: EXTRICATION_ENTRAPPED",
  "RESCUE: TRANSPORTATION: MOTOR_VEHICLE_EXTRICATION_ENTRAPPED",
  "RESCUE: TRANSPORTATION: TRAIN_RAIL_COLLISION_DERAILMENT",
  "RESCUE: TRANSPORTATION: AVIATION_COLLISION_CRASH",
  "RESCUE: TRANSPORTATION: AVIATION_STANDBY",
  "RESCUE: WATER: PERSON_IN_WATER_STANDING",
  "RESCUE: WATER: PERSON_IN_WATER_SWIFTWATER",
  "RESCUE: WATER: WATERCRAFT_IN_DISTRESS",
  "NOEMERG: FALSE_ALARM: INTENTIONAL_FALSE_ALARM",
  "NOEMERG: FALSE_ALARM: MALFUNCTIONING_ALARM",
  "NOEMERG: FALSE_ALARM: ACCIDENTAL_ALARM",
  "NOEMERG: FALSE_ALARM: OTHER_FALSE_CALL",
  "NOEMERG: FALSE_ALARM: BOMB_SCARE",
  "NOEMERG: GOOD_INTENT: NO_INCIDENT_FOUND_LOCATION_ERROR",
  "NOEMERG: GOOD_INTENT: CONTROLLED_BURNING_AUTHORIZED",
  "NOEMERG: GOOD_INTENT: SMOKE_FROM_NONHOSTILE_SOURCE",
  "NOEMERG: GOOD_INTENT: INVESTIGATE_HAZARDOUS_RELEASE",
  "NOEMERG: CANCELLED",
  "LAWENFORCE",
  "MEDICAL: ILLNESS",
  "MEDICAL: INJURY",
];

const NERIS_ACTION_TACTIC_VALUES: readonly string[] = [
  "EMERGENCY_MEDICAL_CARE: PATIENT_ASSESSMENT",
  "EMERGENCY_MEDICAL_CARE: PROVIDE_BASIC_LIFE_SUPPORT",
  "EMERGENCY_MEDICAL_CARE: PROVIDE_ADVANCED_LIFE_SUPPORT",
  "EMERGENCY_MEDICAL_CARE: PROVIDE_TRANSPORT",
  "EMERGENCY_MEDICAL_CARE: PATIENT_REFERRAL",
  "COMMAND_AND_CONTROL: ESTABLISH_INCIDENT_COMMAND",
  "COMMAND_AND_CONTROL: SAFETY_OFFICER_ASSIGNED",
  "COMMAND_AND_CONTROL: PIO_ASSIGNED",
  "COMMAND_AND_CONTROL: NOTIFY_OTHER_AGENCIES",
  "COMMAND_AND_CONTROL: INCIDENT_ASSESSMENT_COMPLETED",
  "COMMAND_AND_CONTROL: ACCOUNTABILITY_OFFICER_ASSIGNED",
  "FORCIBLE_ENTRY",
  "INVESTIGATION",
  "SUPPRESSION: STRUCTURAL_FIRE_SUPPRESSION: INTERIOR",
  "SUPPRESSION: STRUCTURAL_FIRE_SUPPRESSION: EXTERIOR",
  "SUPPRESSION: STRUCTURAL_FIRE_SUPPRESSION: EXTERIOR_AND_INTERIOR",
  "SUPPRESSION: OUTSIDE_FIRE_SUPPRESSION: ESTABLISH_FIRE_LINES",
  "SUPPRESSION: OUTSIDE_FIRE_SUPPRESSION: BACKBURN",
  "SUPPRESSION: OUTSIDE_FIRE_SUPPRESSION: CONFINEMENT",
  "SUPPRESSION: OUTSIDE_FIRE_SUPPRESSION: STRUCTURE_PROTECTION",
  "SUPPRESSION: OUTSIDE_FIRE_SUPPRESSION: FIRE_CONTROL_EXTINGUISHMENT",
  "SUPPRESSION: OUTSIDE_FIRE_SUPPRESSION: FIRE_RETARDANT_DROP",
  "SUPPRESSION: OUTSIDE_FIRE_SUPPRESSION: WATER_DROP",
  "CONTAINMENT: OUTSIDE_FIRE_SUPPRESSION: HAND_CREW_FUEL_BREAK",
  "CONTAINMENT: OUTSIDE_FIRE_SUPPRESSION: DOZER_FUEL_BREAK",
  "VENTILATION: VERTICAL",
  "VENTILATION: VERTICAL: PRIOR_TO_SUPPRESSION",
  "VENTILATION: VERTICAL: DURING_SUPPRESSION",
  "VENTILATION: VERTICAL: POST_SUPPRESSION",
  "VENTILATION: HORIZONTAL",
  "VENTILATION: HORIZONTAL: PRIOR_TO_SUPPRESSION",
  "VENTILATION: HORIZONTAL: DURING_SUPPRESSION",
  "VENTILATION: HORIZONTAL: POST_SUPPRESSION",
  "VENTILATION: POSITIVE_PRESSURE",
  "VENTILATION: POSITIVE_PRESSURE: PRIOR_TO_SUPPRESSION",
  "VENTILATION: POSITIVE_PRESSURE: DURING_SUPPRESSION",
  "VENTILATION: POSITIVE_PRESSURE: POST_SUPPRESSION",
  "VENTILATION: HYDRAULIC",
  "VENTILATION: HYDRAULIC: PRIOR_TO_SUPPRESSION",
  "VENTILATION: HYDRAULIC: DURING_SUPPRESSION",
  "VENTILATION: HYDRAULIC: POST_SUPPRESSION",
  "SEARCH_STRUCTURE: DOOR_INITIATED_SEARCH",
  "SEARCH_STRUCTURE: DOOR_INITIATED_SEARCH: PRIOR_TO_SUPPRESSION",
  "SEARCH_STRUCTURE: DOOR_INITIATED_SEARCH: DURING_SUPPRESSION",
  "SEARCH_STRUCTURE: DOOR_INITIATED_SEARCH: POST_SUPPRESSION",
  "SEARCH_STRUCTURE: WINDOW_INITIATED_SEARCH",
  "SEARCH_STRUCTURE: WINDOW_INITIATED_SEARCH: PRIOR_TO_SUPPRESSION",
  "SEARCH_STRUCTURE: WINDOW_INITIATED_SEARCH: DURING_SUPPRESSION",
  "SEARCH_STRUCTURE: WINDOW_INITIATED_SEARCH: POST_SUPPRESSION",
  "NON_STRUCTURE_SEARCH: SEARCH_AREA_OF_COLLAPSE",
  "NON_STRUCTURE_SEARCH: SEARCH_UNDERGROUND_INFRASTRUCTURE",
  "NON_STRUCTURE_SEARCH: WIDE_AREA_OUTDOOR_SEARCH",
  "NON_STRUCTURE_SEARCH: SEARCH_WATERWAY",
  "NON_STRUCTURE_SEARCH: BODY_RECOVERY",
  "NON_STRUCTURE_SEARCH: USAR_K9_SEARCH",
  "SALVAGE_AND_OVERHAUL",
  "PERSONNEL_CONTAMINATION_REDUCTION: ON_SCENE_CONTAMINATION_REDUCTION",
  "PERSONNEL_CONTAMINATION_REDUCTION: CLEAN_CAB_TRANSPORT",
  "PERSONNEL_CONTAMINATION_REDUCTION: PPE_WASHED_POST_INCIDENT",
  "HAZARDOUS_SITUATION_MITIGATION: TAKE_SAMPLES",
  "HAZARDOUS_SITUATION_MITIGATION: SPILL_CONTROL",
  "HAZARDOUS_SITUATION_MITIGATION: LEAK_STOP",
  "HAZARDOUS_SITUATION_MITIGATION: REMOVE_HAZARD",
  "HAZARDOUS_SITUATION_MITIGATION: DECONTAMINATION",
  "HAZARDOUS_SITUATION_MITIGATION: ATMOSPHERIC_MONITORING_INTERIOR",
  "HAZARDOUS_SITUATION_MITIGATION: ATMOSPHERIC_MONITORING_EXTERIOR_FENCELINE",
  "PROVIDE_EVACUATION_SUPPORT: CONNECTED_INTERIOR_SPACES",
  "PROVIDE_EVACUATION_SUPPORT: REMOTE_INTERIOR_SPACES",
  "PROVIDE_EVACUATION_SUPPORT: NEARBY_BUILDINGS",
  "PROVIDE_EVACUATION_SUPPORT: LARGE_AREA",
  "PROVIDE_EQUIPMENT: PROVIDE_SPECIAL_EQUIPMENT",
  "PROVIDE_EQUIPMENT: PROVIDE_LIGHT",
  "PROVIDE_EQUIPMENT: PROVIDE_ELECTRICAL_POWER",
  "PROVIDE_EQUIPMENT: PROVIDE_DRONE_VIDEO_EQUIPMENT",
  "PROVIDE_SERVICES: RESTORE_SPRINKLER_SYSTEM",
  "PROVIDE_SERVICES: RESTORE_RESET_ALARM_SYSTEM",
  "PROVIDE_SERVICES: SHUT_DOWN_ALARM",
  "PROVIDE_SERVICES: SHUT_DOWN_SPRINKLER_SYSTEM",
  "PROVIDE_SERVICES: SECURE_PROPERTY",
  "PROVIDE_SERVICES: REMOVE_WATER",
  "PROVIDE_SERVICES: ASSIST_UNINJURED_PERSON",
  "PROVIDE_SERVICES: ASSIST_ANIMAL",
  "PROVIDE_SERVICES: PROVIDE_APPARATUS_WATER",
  "PROVIDE_SERVICES: CONTROL_CROWD",
  "PROVIDE_SERVICES: CONTROL_TRAFFIC",
  "PROVIDE_SERVICES: DAMAGE_ASSESSMENT",
  "INFORMATION_ENFORCEMENT: REFER_TO_PROPER_AHJ",
  "INFORMATION_ENFORCEMENT: ENFORCE_CODE_OR_LAW",
  "INFORMATION_ENFORCEMENT: PROVIDE_PUBLIC_INFORMATION",
];

const NERIS_NO_ACTION_VALUES: readonly string[] = [
  "CANCELLED",
  "STAGED_STANDBY",
  "NO_INCIDENT_FOUND",
];

const NERIS_AID_DIRECTION_VALUES: readonly string[] = ["GIVEN", "RECEIVED"];

const NERIS_AID_TYPE_VALUES: readonly string[] = [
  "SUPPORT_AID",
  "IN_LIEU_AID",
  "ACTING_AS_AID",
];

const NERIS_AID_NONFD_VALUES: readonly string[] = [
  "LAW_ENFORCEMENT",
  "SOCIAL_SERVICES",
  "ANIMAL_SERVICES",
  "HOUSING_SERVICES",
  "UTILITIES_PUBLIC_WORKS",
  "REMEDIATION_SERVICES",
];

const NERIS_ENUM_VALUES = {
  location_use: [
    "AGRICULTURE_STRUCT||ANIMAL_PROCESSING",
    "AGRICULTURE_STRUCT||AUCTION_FEEDLOT",
    "AGRICULTURE_STRUCT||FARM_BUILDING",
    "AGRICULTURE_STRUCT||STORAGE_SILO",
    "AGRICULTURE_STRUCT||VETERINARY_LIVESTOCK",
    "ASSEMBLY||COMMUNITY_CENTER",
    "ASSEMBLY||CONVENTION_CENTER",
    "ASSEMBLY||INDOOR_ARENA",
    "ASSEMBLY||MUSEUM_EXHIBIT_HALL_LIBRARY",
    "ASSEMBLY||OUTDOOR_ARENA_AMPHITHEATER_PARK",
    "ASSEMBLY||RELIGIOUS",
    "ASSEMBLY||TEMP_OUTDOOR_STRUCT_EVENT",
    "COMMERCIAL||BAR_NIGHTCLUB",
    "COMMERCIAL||ENTERTAINMENT_RECREATION",
    "COMMERCIAL||OFFICE_OTHER_TECHNICAL_SERVICES",
    "COMMERCIAL||RESTAURANT_CAFE",
    "COMMERCIAL||RETAIL_WHOLESALE_TRADE",
    "COMMERCIAL||THEATERS_STUDIO",
    "COMMERCIAL||VEHICLE_FUELING_CHARGING_STATION",
    "COMMERCIAL||VEHICLE_REPAIR_SERVICES",
    "COMMERCIAL||VETERINARY_PET",
    "EDUCATION||COLLEGES_UNIVERSITIES",
    "EDUCATION||DORMITORY_HOUSING",
    "EDUCATION||K_12_SCHOOLS",
    "EDUCATION||OTHER_EDUCATIONAL_BUILDINGS",
    "EDUCATION||PREK_DAYCARE",
    "GOVERNMENT||FIRE_MEDICAL_STATION",
    "GOVERNMENT||GENERAL_SERVICES",
    "GOVERNMENT||JAIL_PRISON_REFORMATORY",
    "GOVERNMENT||NON_CIVILIAN_STRUCTURES",
    "GOVERNMENT||POLICE_EMERGENCY_STATION",
    "HEALTH_CARE||ALCOHOL_DRUG_REHABILITATION_CENTER",
    "HEALTH_CARE||HOSPITAL_24_HOUR_MEDICAL_FACILITIES",
    "HEALTH_CARE||MEDICAL_OFFICE_CLINIC",
    "HEALTH_CARE||NURSING_HOME_ASSISTED_LIVING_RESIDENCE_ONSITE",
    "INDUSTRIAL||CHEMICAL",
    "INDUSTRIAL||COLD_STORAGE",
    "INDUSTRIAL||FOOD_DRUGS",
    "INDUSTRIAL||HEAVY",
    "INDUSTRIAL||LIGHT",
    "INDUSTRIAL||METALS_MINERALS_PROCESSING",
    "OUTDOOR_INDUSTRIAL||CONSTRUCTION_SITE",
    "OUTDOOR_INDUSTRIAL||DUMP_LANDFILL",
    "OUTDOOR_INDUSTRIAL||INDUSTRIAL_YARD",
    "OUTDOOR_INDUSTRIAL||MINE",
    "OUTDOOR||CAMP_SITE",
    "OUTDOOR||FOREST_GRASSLANDS_WOODLAND_WILDLAND_AREAS",
    "OUTDOOR||GROUND_VACANT_LAND",
    "OUTDOOR||HIKING_TRAIL",
    "OUTDOOR||OPEN_WATER",
    "OUTDOOR||ORCHARD_CROPS_FARMLAND",
    "OUTDOOR||PLAYGROUND_PARK_RECREATIONAL_AREA",
    "OUTDOOR||WATERFRONT",
    "RESIDENTIAL||ATTACHED_SINGLE_FAMILY_DWELLING",
    "RESIDENTIAL||CONGREGATE_HOUSING",
    "RESIDENTIAL||DETATCHED_GARAGE",
    "RESIDENTIAL||DETATCHED_SINGLE_FAMILY_DWELLING",
    "RESIDENTIAL||MANUFACTURED_MOBILE_HOME",
    "RESIDENTIAL||MULTI_FAMILY_HIGHRISE_DWELLING",
    "RESIDENTIAL||MULTI_FAMILY_LOWRISE_DWELLING",
    "RESIDENTIAL||MULTI_FAMILY_MIDRISE_DWELLING",
    "RESIDENTIAL||TEMPORARY_LODGING_HOTEL_MOTEL",
    "RESIDENTIAL||UNHOUSED_TEMPORARY_SHELTER",
    "ROADWAY_ACCESS||BRIDGE",
    "ROADWAY_ACCESS||HIGHWAY_INTERSTATE",
    "ROADWAY_ACCESS||LIMITED_ACCESS_HIGHWAY_INTERSTATE",
    "ROADWAY_ACCESS||PARKING_LOT_GARAGE",
    "ROADWAY_ACCESS||RAILROAD_RAILYARD",
    "ROADWAY_ACCESS||SIDEWALK",
    "ROADWAY_ACCESS||STREET",
    "ROADWAY_ACCESS||TUNNEL",
    "STORAGE||STORAGE_MULTI_TENANT",
    "STORAGE||STORAGE_PORTABLE_BUILDING",
    "STORAGE||STORAGE_SINGLE_TENANT",
    "UNCLASSIFIED||UNCLASSIFIED",
    "UTILITY_MISC||ENERGY_FACILITY_INFRASTRUCTURE",
    "UTILITY_MISC||TRANSPORTATION_STATION_HUB_AREA",
    "UTILITY_MISC||TRASH_RECYCLING_FACILITY",
    "UTILITY_MISC||WATER_SANITATION_FACILITY_INFRASTRUCTURE",
  ],
  location_place: [
    "AIRCRAFT",
    "AIRPORT",
    "ARENA",
    "AUTOMOBILE",
    "BANK",
    "BAR",
    "BICYCLE",
    "BUS",
    "BUS_STATION",
    "CAFE",
    "CLASSROOM",
    "CLUB",
    "CONSTRUCTION",
    "CONVENTION_CENTER",
    "GOVERNMENT",
    "HOSPITAL",
    "HOTEL",
    "INDUSTRIAL",
    "LIBRARY",
    "MOTORCYCLE",
    "MUSEUM",
    "OFFICE",
    "OTHER",
    "OUTDOORS",
    "PARKING",
    "PLACE_OF_WORSHIP",
    "PRISON",
    "PUBLIC",
    "PUBLIC_TRANSPORT",
    "RESIDENCE",
    "RESTAURANT",
    "SCHOOL",
    "SHOPPING_AREA",
    "STADIUM",
    "STORE",
    "STREET",
    "THEATER",
    "TRAIN",
    "TRAIN_STATION",
    "TRUCK",
    "UNDERWAY",
    "UNKNOWN",
    "WAREHOUSE",
    "WATER",
    "WATERCRAFT",
  ],
  state: [
    "AL",
    "AK",
    "AS",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "FM",
    "GA",
    "GU",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MH",
    "MN",
    "MS",
    "MO",
    "MP",
    "MT",
    "NA",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "PR",
    "PW",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UM",
    "UT",
    "VT",
    "VA",
    "VI",
    "WA",
    "WV",
    "WI",
    "WY",
  ],
  country: [
    "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR", "AS", "AT", "AU", "AW", "AX",
    "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ",
    "BR", "BS", "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK",
    "CL", "CM", "CN", "CO", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM",
    "DO", "DZ", "EC", "EE", "EG", "EH", "ER", "ES", "ET", "FI", "FJ", "FK", "FM", "FO", "FR",
    "GA", "GB", "GD", "GE", "GF", "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS",
    "GT", "GU", "GW", "GY", "HK", "HM", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IM", "IN",
    "IO", "IQ", "IR", "IS", "IT", "JE", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN",
    "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV",
    "LY", "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MQ",
    "MR", "MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NC", "NE", "NF", "NG", "NI",
    "NL", "NO", "NP", "NR", "NU", "NZ", "OM", "PA", "PE", "PF", "PG", "PH", "PK", "PL", "PM",
    "PN", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS", "RU", "RW", "SA", "SB", "SC",
    "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS", "ST", "SV",
    "SX", "SY", "SZ", "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO", "TR",
    "TT", "TV", "TW", "TZ", "UA", "UG", "UM", "US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI",
    "VN", "VU", "WF", "WS", "YE", "YT", "ZA", "ZM", "ZW",
  ],
  vacancy: [
    "ABANDONED",
    "DAMAGE_DECAY",
    "FORECLOSURE",
    "FOR_SALE_LEASE",
    "NEW_CONSTRUCTION_REMODEL",
    "SEASONAL_OCCASIONALLY_OCCUPIED",
    "UNKNOWN",
  ],
  location_direction: ["EASTBOUND", "NORTHBOUND", "SOUTHBOUND", "WESTBOUND"],
  location_cross_street: [
    "CLOSEST",
    "INCIDENT_IN_INTERSECTION",
    "SECOND_CLOSEST",
  ],
  unit_type: [
    "AIR_EMS",
    "AIR_LIGHT",
    "AIR_RECON",
    "AIR_TANKER",
    "ALS_AMB",
    "ARFF",
    "ATV_EMS",
    "ATV_FIRE",
    "BLS_AMB",
    "BOAT",
    "BOAT_LARGE",
    "CHIEF_STAFF_COMMAND",
    "CREW",
    "CREW_TRANS",
    "DECON",
    "DOZER",
    "EMS_NOTRANS",
    "EMS_SUPV",
    "ENGINE_STRUCT",
    "ENGINE_WUI",
    "FOAM",
    "HAZMAT",
    "HELO_FIRE",
    "HELO_GENERAL",
    "HELO_RESCUE",
    "INVEST",
    "LADDER_QUINT",
    "LADDER_SMALL",
    "LADDER_TALL",
    "LADDER_TILLER",
    "MAB",
    "MOBILE_COMMS",
    "MOBILE_ICP",
    "OTHER_GROUND",
    "PLATFORM",
    "PLATFORM_QUINT",
    "POV",
    "QUINT_TALL",
    "REHAB",
    "RESCUE_HEAVY",
    "RESCUE_LIGHT",
    "RESCUE_MEDIUM",
    "RESCUE_USAR",
    "RESCUE_WATER",
    "SCBA",
    "TENDER",
    "UAS_FIRE",
    "UAS_RECON",
    "UTIL",
  ],
  response_mode: ["EMERGENT", "NON_EMERGENT"],
  hazard_disposition: [
    "COMPLETED_FIRE_SERVICE_ONLY",
    "COMPLETED_WITH_FIRE_SERVICE_PRESENT",
    "RELEASED_TO_COUNTY_AGENCY",
    "RELEASED_TO_FEDERAL_AGENCY",
    "RELEASED_TO_LOCAL_AGENCY",
    "RELEASED_TO_PRIVATE_AGENCY",
    "RELEASED_TO_PROPERTY_OWNER",
    "RELEASED_TO_STATE_AGENCY",
  ],
  emerg_haz_elec: [
    "CONSUMER_PRODUCTS||APPLIANCE_TOOL",
    "CONSUMER_PRODUCTS||CELL_PHONE",
    "CONSUMER_PRODUCTS||COMPUTER_TABLET",
    "CONSUMER_PRODUCTS||ELECTRONIC_CIGARETTE",
    "CONSUMER_PRODUCTS||OTHER",
    "CONSUMER_PRODUCTS||POWER_BANK",
    "CONSUMER_PRODUCTS||TOY",
    "ELECTRIC_VEHICLE||BOAT_COMMERCIAL||FUEL_CELL",
    "ELECTRIC_VEHICLE||BOAT_COMMERCIAL||FULL_ELECTRIC",
    "ELECTRIC_VEHICLE||BOAT_COMMERCIAL||HYBRID",
    "ELECTRIC_VEHICLE||BOAT_COMMERCIAL||PLUG_IN_HYBRID",
    "ELECTRIC_VEHICLE||BOAT_RECREATIONAL||FUEL_CELL",
    "ELECTRIC_VEHICLE||BOAT_RECREATIONAL||FULL_ELECTRIC",
    "ELECTRIC_VEHICLE||BOAT_RECREATIONAL||HYBRID",
    "ELECTRIC_VEHICLE||BOAT_RECREATIONAL||PLUG_IN_HYBRID",
    "ELECTRIC_VEHICLE||BUS_RR||FUEL_CELL",
    "ELECTRIC_VEHICLE||BUS_RR||FULL_ELECTRIC",
    "ELECTRIC_VEHICLE||BUS_RR||HYBRID",
    "ELECTRIC_VEHICLE||BUS_RR||PLUG_IN_HYBRID",
    "ELECTRIC_VEHICLE||CAR_RR||FUEL_CELL",
    "ELECTRIC_VEHICLE||CAR_RR||FULL_ELECTRIC",
    "ELECTRIC_VEHICLE||CAR_RR||HYBRID",
    "ELECTRIC_VEHICLE||CAR_RR||PLUG_IN_HYBRID",
    "ELECTRIC_VEHICLE||LIGHT_EV_NRR||FUEL_CELL",
    "ELECTRIC_VEHICLE||LIGHT_EV_NRR||FULL_ELECTRIC",
    "ELECTRIC_VEHICLE||LIGHT_EV_NRR||HYBRID",
    "ELECTRIC_VEHICLE||LIGHT_EV_NRR||PLUG_IN_HYBRID",
    "ELECTRIC_VEHICLE||OTHER||FUEL_CELL",
    "ELECTRIC_VEHICLE||OTHER||FULL_ELECTRIC",
    "ELECTRIC_VEHICLE||OTHER||HYBRID",
    "ELECTRIC_VEHICLE||OTHER||PLUG_IN_HYBRID",
    "ELECTRIC_VEHICLE||TRUCK_COMMERCIAL_RR||FUEL_CELL",
    "ELECTRIC_VEHICLE||TRUCK_COMMERCIAL_RR||FULL_ELECTRIC",
    "ELECTRIC_VEHICLE||TRUCK_COMMERCIAL_RR||HYBRID",
    "ELECTRIC_VEHICLE||TRUCK_COMMERCIAL_RR||PLUG_IN_HYBRID",
    "ELECTRIC_VEHICLE||TRUCK_PASSENGER_RR||FUEL_CELL",
    "ELECTRIC_VEHICLE||TRUCK_PASSENGER_RR||FULL_ELECTRIC",
    "ELECTRIC_VEHICLE||TRUCK_PASSENGER_RR||HYBRID",
    "ELECTRIC_VEHICLE||TRUCK_PASSENGER_RR||PLUG_IN_HYBRID",
    "ENERGY_STORAGE_SYSTEM||BATTERY",
    "ENERGY_STORAGE_SYSTEM||COMPRESSED_AIR",
    "ENERGY_STORAGE_SYSTEM||FLYWHEEL",
    "ENERGY_STORAGE_SYSTEM||HYDROELECTRIC",
    "ENERGY_STORAGE_SYSTEM||OTHER",
    "E_MOBILITY||ELECTRIC_SCOOTER_MOPED",
    "E_MOBILITY||OTHER",
    "E_MOBILITY||PERSONAL_MOBILITY_ASSIST",
    "E_MOBILITY||POWER_ASSISTED_BICYCLE",
  ],
  emerg_haz_suppression: [
    "BATTERY_PENETRATION",
    "FIRE_BLANKET",
    "RUN_COURSE",
    "SUBMERGE_BURY",
    "SUPPRESSION_WATER_ADDITIVE",
    "SUPPRESSION_WATER_ONLY",
  ],
  emerg_haz_pv: [
    "OTHER",
    "PANEL_POWER_GENERATION",
    "PANEL_WATER_HEATING",
    "THIN_FILM_POWER_GENERATION",
    "TILE_POWER_GENERATION",
  ],
  emerg_haz_pv_ign: ["SOURCE", "TARGET"],
  hazard_dot: [
    "CORROSIVES",
    "EXPLOSIVES",
    "FLAMMABLE_LIQUIDS",
    "FLAMMABLE_SOLIDS",
    "GASES",
    "MISCELLANEOUS_DANGEROUS_SUBSTANCES",
    "OXIDIZERS",
    "POISONS_AND_ETIOLOGIC_MATERIALS",
    "RADIOACTIVE_MATERIALS",
  ],
  hazard_unit: [
    "GAS_CUBIC_CENTIMETER",
    "GAS_CUBIC_FOOT",
    "GAS_CUBIC_INCH",
    "GAS_CUBIC_METER",
    "GAS_POUND",
    "LIQUID_CUBIC_CENTIMETER",
    "LIQUID_CUP",
    "LIQUID_GALLON",
    "LIQUID_GRAM",
    "LIQUID_KILOGRAM",
    "LIQUID_LITER",
    "LIQUID_MILLIGRAM",
    "LIQUID_MILLILITER",
    "LIQUID_OUNCE",
    "LIQUID_PINT",
    "LIQUID_POUND",
    "LIQUID_QUART",
    "LIQUID_TABLESPOON",
    "LIQUID_TEASPOON",
    "RADIOACTIVE_CURIE",
    "RADIOACTIVE_MEGABECQUEREL",
    "RADIOACTIVE_MICROCURIE",
    "RADIOACTIVE_MILLICURIE",
    "RADIOACTIVE_TERABECQUEREL",
    "SOLID_GRAM",
    "SOLID_KILOGRAM",
    "SOLID_LITER",
    "SOLID_MILLIGRAM",
    "SOLID_OUNCE",
    "SOLID_POUND",
    "SOLID_TABLESPOON",
    "SOLID_TEASPOON",
    "SOLID_TON",
  ],
  source_target: ["SOURCE", "TARGET", "UNKNOWN"],
  fire_water_supply: [
    "DRAFT_FROM_STATIC_SOURCE",
    "FOAM_ADDITIVE",
    "HYDRANT_GREATER_500",
    "HYDRANT_LESS_500",
    "NONE",
    "NURSE_OTHER_APPARATUS",
    "SUPPLY_FROM_FIRE_BOAT",
    "TANK_WATER",
    "WATER_TENDER_SHUTTLE",
  ],
  fire_invest_need: [
    "NO",
    "NOT_APPLICABLE",
    "NOT_EVALUATED",
    "NO_CAUSE_OBVIOUS",
    "OTHER",
    "YES",
  ],
  fire_invest_types: [
    "INVESTIGATED_BY_ARSON_FIRE_INVESTIGATOR",
    "INVESTIGATED_BY_INSURANCE",
    "INVESTIGATED_BY_NONFIRE_LAW_ENFORCEMENT",
    "INVESTIGATED_BY_OTHER",
    "INVESTIGATED_BY_OUTSIDE_AGENCY",
    "INVESTIGATED_BY_STATE_FIRE_MARSHAL",
    "INVESTIGATED_ON_SCENE_RESOURCE",
    "NONE",
  ],
  fire_suppression_appliance: [
    "AIRATTACK_HELITACK",
    "BOOSTER_FIRE_HOSE",
    "BUILDING_FDC",
    "BUILDING_STANDPIPE",
    "ELEVATED_MASTER_STREAM_STANDPIPE",
    "FIRE_EXTINGUISHER",
    "GROUND_MONITOR",
    "MASTER_STREAM",
    "MEDIUM_DIAMETER_FIRE_HOSE",
    "NONE",
    "OTHER",
    "SMALL_DIAMETER_FIRE_HOSE",
  ],
  fire_condition_arrival: [
    "FIRE_OUT_UPON_ARRIVAL",
    "FIRE_SPREAD_BEYOND_STRUCTURE",
    "NO_SMOKE_FIRE_SHOWING",
    "SMOKE_FIRE_SHOWING",
    "SMOKE_SHOWING",
    "STRUCTURE_INVOLVED",
  ],
  fire_cause_in: [
    "ACT_OF_NATURE",
    "BATTERY_POWER_STORAGE",
    "CHEMICAL",
    "COOKING",
    "ELECTRICAL",
    "EXPLOSIVES_FIREWORKS",
    "HEAT_FROM_ANOTHER_OBJECT",
    "INCENDIARY",
    "OPEN_FLAME",
    "OPERATING_EQUIPMENT",
    "OTHER_HEAT_SOURCE",
    "SMOKING_MATERIALS_ILLICIT_DRUGS",
    "UNABLE_TO_BE_DETERMINED",
  ],
  fire_cause_out: [
    "BATTERY_POWER_STORAGE",
    "DEBRIS_OPEN_BURNING",
    "EQUIPMENT_VEHICLE_USE",
    "FIREARMS_EXPLOSIVES",
    "FIREWORKS",
    "INCENDIARY",
    "NATURAL",
    "POWER_GEN_TRANS_DIST",
    "RAILROAD_OPS_MAINTENANCE",
    "RECREATION_CEREMONY",
    "SMOKING_MATERIALS_ILLICIT_DRUGS",
    "SPREAD_FROM_CONTROLLED_BURN",
    "STRUCTURE",
    "UNABLE_TO_BE_DETERMINED",
  ],
  full_partial: ["EXTENT_UNKNOWN", "FULL", "PARTIAL"],
  alarm_smoke: [
    "BED_SHAKER",
    "COMBINATION",
    "HARDWIRED",
    "HARD_OF_HEARING_WITH_STROBE",
    "INTERCONNECTED",
    "LONG_LIFE_BATTERY_POWERED",
    "REPLACEABLE_BATTERY_POWERED",
    "UNKNOWN",
  ],
  alarm_operation: [
    "FAILED_TO_OPERATE",
    "INSUFFICIENT_SOURCE",
    "NO_OCCUPANT_TO_NOTIFY",
    "OPERATED_ALERTED_OCCUPANT",
    "OPERATED_FAILED_TO_ALERT_OCCUPANT",
  ],
  alarm_failure: [
    "DEVICE_MALFUNCTION",
    "EXPIRED",
    "IMPROPER_INSTALLATION",
    "NO_BATTERY",
    "OTHER_NON_FUNCTIONAL_CAUSE",
    "TAMPER",
    "UNABLE_TO_DETERMINE",
  ],
  alarm_fire: ["AUTOMATIC", "MANUAL", "MANUAL_AND_AUTOMATIC"],
  alarm_other: [
    "CARBON_MONOXIDE",
    "HEAT_DETECTOR",
    "NATURAL_GAS",
    "OTHER_CHEMICAL_DETECTOR",
  ],
  suppress_fire: [
    "CLEAN_AGENT_SYSTEM",
    "DELUGE_SYSTEM",
    "DRY_PIPE_SPRINKLER_SYSTEM",
    "INDUSTRIAL_DRY_CHEM_SYSTEM",
    "OTHER",
    "PRE_ACTION_SYSTEM",
    "UNKNOWN",
    "WET_PIPE_SPRINKLER_SYSTEM",
  ],
  suppress_operation: ["NO_OPERATION", "OPERATED_EFFECTIVE", "OPERATED_NOT_EFFECTIVE"],
  suppress_no_operation: [
    "INSUFFICIENT_SOURCE",
    "INSUFFICIENT_WATER_SUPPLY",
    "SYSTEM_DAMAGED_COMPROMISED",
    "SYSTEM_INOPERABLE",
    "SYSTEM_NOT_SUITABLE",
    "SYSTEM_SHUTOFF_DURING_INCIDENT",
    "SYSTEM_SHUTOFF_PRIOR_TO_INCIDENT",
    "UNABLE_TO_DETERMINE",
  ],
  suppress_cooking: [
    "COMMERCIAL_HOOD_SUPPRESSION",
    "ELECTRIC_POWER_CUTOFF_DEVICE",
    "OTHER",
    "RESIDENTIAL_HOOD_MOUNTED",
    "TEMPERATURE_LIMITING_STOVE",
  ],
  suppress_time: ["DURING_SUPPRESSION", "POST_SUPPRESSION", "PRE_SUPPRESSION"],
  exposure_damage: ["MAJOR_DAMAGE", "MINOR_DAMAGE", "MODERATE_DAMAGE", "NO_DAMAGE"],
  exposure_item: ["OBJECT_OTHER", "OUTDOOR_ENVIRONMENT", "STRUCTURE", "VEHICLE"],
  displace_cause_exposure: [
    "COLLAPSE",
    "FIRE",
    "HAZARDOUS_SITUATION",
    "OTHER",
    "SMOKE",
    "UTILITIES",
    "WATER",
  ],
  displace_cause_incident: [
    "COLLAPSE",
    "FIRE",
    "HAZARDOUS_SITUATION",
    "OTHER",
    "SMOKE",
    "UTILITIES",
    "WATER",
  ],
  medical_patient_care: [
    "PATIENT_DEAD_ON_ARRIVAL",
    "PATIENT_EVALUATED_CARE_PROVIDED",
    "PATIENT_EVALUATED_NO_CARE_REQUIRED",
    "PATIENT_EVALUATED_REFUSED_CARE",
    "PATIENT_REFUSED_EVALUATION_CARE",
    "PATIENT_SUPPORT_SERVICES_PROVIDED",
  ],
  medical_patient_status: ["IMPROVED", "UNCHANGED", "WORSE"],
  medical_transport: [
    "NONPATIENT_TRANSPORT",
    "NO_TRANSPORT",
    "OTHER_AGENCY_TRANSPORT",
    "PATIENT_REFUSED_TRANSPORT",
    "TRANSPORT_BY_EMS_UNIT",
  ],
  rescue_action: [
    "BRACE_WALL_INFRASTRUCTURE",
    "BREAK_BREACH_WALL",
    "HYDRAULIC_TOOL_USE",
    "NONE",
    "ROPE_RIGGING",
    "SUPPLY_AIR",
    "TRENCH_SHORING",
    "UNDERWATER_DIVE",
    "VENTILATION",
  ],
  rescue_impediment: [
    "ACCESS_LIMITATIONS",
    "HOARDING_CONDITIONS",
    "IMPAIRED_PERSON",
    "NONE",
    "OTHER",
    "PHYSICAL_MEDICAL_CONDITIONS_PERSON",
  ],
  rescue_presence_known: ["KNOWN_ARRIVAL", "KNOWN_DISPATCH", "KNOWN_DURING"],
  rescue_mode: [
    "DISENTANGLEMENT",
    "EXTRICATION",
    "OTHER",
    "RECOVERY",
    "REMOVAL_FROM_STRUCTURE",
  ],
  rescue_path: ["REMOVAL_ALONG_ALT_PATH", "REMOVAL_ALONG_PRIMARY_PATH"],
  rescue_elevation: ["ON_BED", "ON_FLOOR", "ON_FURNITURE", "OTHER"],
  casualty_cause: [
    "CAUGHT_TRAPPED_BY_FIRE_EXPLOSION",
    "CAUGHT_TRAPPED_BY_OBJECT",
    "COLLAPSE",
    "EXPOSURE",
    "FALL_JUMP",
    "OTHER",
    "STRESS_OVEREXERTION",
    "STRUCK_CONTACT_WITH_OBJECT",
    "VEHICLE_COLLISION",
  ],
  casualty_ppe: [
    "3_4_BOOTS",
    "BRUSH_GEAR",
    "BUNKER_PANTS",
    "FACE_SHIELD_GOGGLES",
    "GLOVES",
    "HELMET",
    "NONE",
    "OTHER_SPECIAL_EQUIPMENT",
    "PASS_DEVICE",
    "PROTECTIVE_HOOD",
    "REFLECTIVE_VEST",
    "RUBBER_KNEE_BOOTS",
    "SCBA",
    "TURNOUT_COAT",
  ],
  gender: [
    "FEMALE",
    "MALE",
    "OTHER_GENDER_IDENTITY",
    "TRANSGENDER_FEMALE_MALE_TO_FEMALE",
    "TRANSGENDER_MALE_FEMALE_TO_MALE",
    "UNKNOWN",
  ],
  race: [
    "AMERICAN_INDIAN_ALASKA_NATIVE",
    "ASIAN",
    "BLACK_AFRICAN_AMERICAN",
    "HISPANIC_LATINO",
    "MIDDLE_EASTERN_NORTH_AFRICAN",
    "NATIVE_HAWAIIAN_PACIFIC_ISLANDER",
    "OTHER",
    "UNKNOWN",
    "WHITE",
  ],
  special_modifier: [
    "ACTIVE_ASSAILANT",
    "COUNTY_LOCAL_DECLARED_DISASTER",
    "FEDERAL_DECLARED_DISASTER",
    "MCI",
    "STATE_DECLARED_DISASTER",
    "URBAN_CONFLAGRATION",
    "VIOLENCE_AGAINST_RESPONDER",
  ],
  yes_no_unknown: ["NO", "UNKNOWN", "YES"],
} as const;

function toApiEnumValue(value: string): string {
  if (value.includes("||")) {
    return value;
  }
  return value
    .split(":")
    .map((segment) => segment.trim())
    .join("||");
}

function formatNerisCodeLabel(value: string): string {
  const apiValue = toApiEnumValue(value);
  return apiValue
    .split("||")
    .map((segment) =>
      segment
        .trim()
        .toLowerCase()
        .replace(/_/g, " ")
        .replace(/\b\w/g, (character) => character.toUpperCase()),
    )
    .join(" / ");
}

function buildOptionsFromValues(values: readonly string[]): NerisValueOption[] {
  const normalizedValues = Array.from(new Set(values.map((value) => toApiEnumValue(value))));
  return normalizedValues.map((value) => ({
    value,
    label: formatNerisCodeLabel(value),
  }));
}

const NERIS_API_ENUM_OPTIONS = Object.fromEntries(
  Object.entries(NERIS_ENUM_VALUES).map(([key, values]) => [
    key,
    buildOptionsFromValues(values),
  ]),
) as Record<keyof typeof NERIS_ENUM_VALUES, NerisValueOption[]>;

export const NERIS_VALUE_SETS = {
  report_status: [
    { value: "Draft", label: "Draft" },
    { value: "In Review", label: "In Review" },
    { value: "Ready for Review", label: "Ready for Review" },
    { value: "Approved", label: "Approved" },
    { value: "Submitted", label: "Submitted" },
  ],
  incident_type: buildOptionsFromValues(NERIS_INCIDENT_TYPE_VALUES),
  action_tactic: buildOptionsFromValues(NERIS_ACTION_TACTIC_VALUES),
  no_action: buildOptionsFromValues(NERIS_NO_ACTION_VALUES),
  aid_direction: buildOptionsFromValues(NERIS_AID_DIRECTION_VALUES),
  aid_type: buildOptionsFromValues(NERIS_AID_TYPE_VALUES),
  aid_nonfd: buildOptionsFromValues(NERIS_AID_NONFD_VALUES),
  aid_agency_type: [
    { value: "FIRE_DEPARTMENT", label: "Fire Department" },
    { value: "NON_FD_AID", label: "Non FD Aid" },
  ],
  aid_department: [
    { value: "FD_CIFPD", label: "Central Islip Fire Department" },
    { value: "FD_WESTBURY", label: "Westbury Fire Department" },
    { value: "FD_LINDENHURST", label: "Lindenhurst Fire Department" },
  ],
  incident_modifier: NERIS_API_ENUM_OPTIONS.special_modifier,
  location_use: NERIS_API_ENUM_OPTIONS.location_use,
  location_place: NERIS_API_ENUM_OPTIONS.location_place,
  state: NERIS_API_ENUM_OPTIONS.state,
  country: NERIS_API_ENUM_OPTIONS.country,
  vacancy: NERIS_API_ENUM_OPTIONS.vacancy,
  location_direction: NERIS_API_ENUM_OPTIONS.location_direction,
  location_cross_street: NERIS_API_ENUM_OPTIONS.location_cross_street,
  unit_type: NERIS_API_ENUM_OPTIONS.unit_type,
  response_mode: NERIS_API_ENUM_OPTIONS.response_mode,
  hazard_disposition: NERIS_API_ENUM_OPTIONS.hazard_disposition,
  emerg_haz_elec: NERIS_API_ENUM_OPTIONS.emerg_haz_elec,
  emerg_haz_suppression: NERIS_API_ENUM_OPTIONS.emerg_haz_suppression,
  emerg_haz_pv: NERIS_API_ENUM_OPTIONS.emerg_haz_pv,
  emerg_haz_pv_ign: NERIS_API_ENUM_OPTIONS.emerg_haz_pv_ign,
  hazard_dot: NERIS_API_ENUM_OPTIONS.hazard_dot,
  hazard_unit: NERIS_API_ENUM_OPTIONS.hazard_unit,
  source_target: NERIS_API_ENUM_OPTIONS.source_target,
  fire_water_supply: NERIS_API_ENUM_OPTIONS.fire_water_supply,
  fire_invest_need: NERIS_API_ENUM_OPTIONS.fire_invest_need,
  fire_invest_types: NERIS_API_ENUM_OPTIONS.fire_invest_types,
  fire_suppression_appliance: NERIS_API_ENUM_OPTIONS.fire_suppression_appliance,
  fire_condition_arrival: NERIS_API_ENUM_OPTIONS.fire_condition_arrival,
  fire_cause_in: NERIS_API_ENUM_OPTIONS.fire_cause_in,
  fire_cause_out: NERIS_API_ENUM_OPTIONS.fire_cause_out,
  full_partial: NERIS_API_ENUM_OPTIONS.full_partial,
  alarm_smoke: NERIS_API_ENUM_OPTIONS.alarm_smoke,
  alarm_operation: NERIS_API_ENUM_OPTIONS.alarm_operation,
  alarm_failure: NERIS_API_ENUM_OPTIONS.alarm_failure,
  alarm_fire: NERIS_API_ENUM_OPTIONS.alarm_fire,
  alarm_other: NERIS_API_ENUM_OPTIONS.alarm_other,
  suppress_fire: NERIS_API_ENUM_OPTIONS.suppress_fire,
  suppress_operation: NERIS_API_ENUM_OPTIONS.suppress_operation,
  suppress_no_operation: NERIS_API_ENUM_OPTIONS.suppress_no_operation,
  suppress_cooking: NERIS_API_ENUM_OPTIONS.suppress_cooking,
  suppress_time: NERIS_API_ENUM_OPTIONS.suppress_time,
  exposure_damage: NERIS_API_ENUM_OPTIONS.exposure_damage,
  exposure_item: NERIS_API_ENUM_OPTIONS.exposure_item,
  exposure_location_detail: buildOptionsFromValues([
    "EXTERNAL_EXPOSURE",
    "INTERNAL_EXPOSURE",
  ]),
  displace_cause_exposure: NERIS_API_ENUM_OPTIONS.displace_cause_exposure,
  displace_cause_incident: NERIS_API_ENUM_OPTIONS.displace_cause_incident,
  medical_patient_care: NERIS_API_ENUM_OPTIONS.medical_patient_care,
  medical_patient_status: NERIS_API_ENUM_OPTIONS.medical_patient_status,
  medical_transport: NERIS_API_ENUM_OPTIONS.medical_transport,
  rescue_action: NERIS_API_ENUM_OPTIONS.rescue_action,
  rescue_impediment: NERIS_API_ENUM_OPTIONS.rescue_impediment,
  rescue_presence_known: NERIS_API_ENUM_OPTIONS.rescue_presence_known,
  rescue_mode: NERIS_API_ENUM_OPTIONS.rescue_mode,
  rescue_path: NERIS_API_ENUM_OPTIONS.rescue_path,
  rescue_elevation: NERIS_API_ENUM_OPTIONS.rescue_elevation,
  casualty_cause: NERIS_API_ENUM_OPTIONS.casualty_cause,
  casualty_ppe: NERIS_API_ENUM_OPTIONS.casualty_ppe,
  gender: NERIS_API_ENUM_OPTIONS.gender,
  race: NERIS_API_ENUM_OPTIONS.race,
  yes_no_unknown: NERIS_API_ENUM_OPTIONS.yes_no_unknown,
  rescue_type: buildOptionsFromValues([
    "RESCUED_BY_FIREFIGHTER",
    "RESCUED_BY_FF_RIT",
    "EVAC_ASSISTED_BY_FIREFIGHTER",
    "RESCUED_BY_NONFIREFIGHTER",
    "SELF_EVACUATION",
    "NO_RESCUE_NEEDED",
  ]),
  casualty_type: buildOptionsFromValues([
    "INJURED_NONFATAL",
    "INJURED_FATAL",
    "UNINJURED",
  ]),
  yes_no: [
    { value: "YES", label: "Yes" },
    { value: "NO", label: "No" },
  ],
  dispatch_code: [
    { value: "AMB.UNRESP-BREATHING", label: "AMB.UNRESP-BREATHING" },
    { value: "FIRE.STRUCT-RESIDENTIAL", label: "FIRE.STRUCT-RESIDENTIAL" },
    { value: "FIRE.AUTO-ACCIDENT", label: "FIRE.AUTO-ACCIDENT" },
    { value: "RESCUE.PUBLIC-ASSIST", label: "RESCUE.PUBLIC-ASSIST" },
  ],
} as const satisfies Record<string, NerisValueOption[]>;

const NERIS_SECTION_NOTE_IDS: NerisSectionId[] = [
  "location",
  "incidentTimes",
  "resources",
  "emergingHazards",
  "hazards",
  "fire",
  "exposures",
  "riskReduction",
  "medical",
  "rescuesCasualties",
  "attachments",
];

const NERIS_SECTION_NOTE_FIELDS: NerisFieldMetadata[] = NERIS_SECTION_NOTE_IDS.map(
  (sectionId) => ({
    id: `${sectionId}_notes`,
    sectionId,
    label: `${NERIS_FORM_SECTIONS.find((section) => section.id === sectionId)?.label ?? sectionId} notes`,
    inputKind: "textarea",
    placeholder: "Enter notes for this section...",
    rows: 6,
    maxLength: 100000,
    layout: "full",
  }),
);

export const NERIS_FORM_FIELDS: NerisFieldMetadata[] = [
  {
    id: "incident_neris_id",
    sectionId: "core",
    label: "Incident NERIS ID",
    inputKind: "readonly",
    required: true,
    layout: "full",
    helperText: "System identifier derived from incident start time.",
  },
  {
    id: "incident_internal_id",
    sectionId: "core",
    label: "Incident number",
    inputKind: "text",
    required: true,
    layout: "half",
  },
  {
    id: "incident_onset_date",
    sectionId: "core",
    label: "Incident onset date",
    inputKind: "date",
    required: true,
    layout: "half",
  },
  {
    id: "incident_onset_time",
    sectionId: "core",
    label: "Incident onset time",
    inputKind: "time",
    required: true,
    layout: "half",
  },
  {
    id: "dispatch_internal_id",
    sectionId: "core",
    label: "Dispatch run number",
    inputKind: "text",
    required: true,
    layout: "half",
  },
  {
    id: "primary_incident_type",
    sectionId: "core",
    label: "Primary incident type",
    inputKind: "select",
    optionsKey: "incident_type",
    required: true,
    layout: "full",
  },
  {
    id: "additional_incident_types",
    sectionId: "core",
    label: "Additional incident type(s)",
    inputKind: "multiselect",
    optionsKey: "incident_type",
    helperText: "Select up to 2 additional types when needed.",
    layout: "full",
  },
  {
    id: "special_incident_modifiers",
    sectionId: "core",
    label: "Special incident modifier(s)",
    inputKind: "multiselect",
    optionsKey: "incident_modifier",
    layout: "full",
  },
  {
    id: "incident_actions_taken",
    sectionId: "core",
    label: "Actions taken",
    inputKind: "multiselect",
    optionsKey: "action_tactic",
    requiredIf: {
      fieldId: "incident_noaction",
      operator: "isEmpty",
    },
    helperText: "Required unless a No action reason is selected.",
    layout: "full",
  },
  {
    id: "incident_noaction",
    sectionId: "core",
    label: "No Action Reason",
    inputKind: "select",
    optionsKey: "no_action",
    requiredIf: {
      fieldId: "incident_actions_taken",
      operator: "isEmpty",
    },
    helperText: "Required if no actions are entered.",
    layout: "full",
  },
  {
    id: "dispatch_automatic_alarm",
    sectionId: "core",
    label: "Automatic alarm",
    inputKind: "select",
    optionsKey: "yes_no",
    required: true,
    layout: "half",
  },
  {
    id: "fd_neris_id",
    sectionId: "core",
    label: "Department NERIS ID",
    inputKind: "text",
    required: true,
    layout: "half",
  },
  {
    id: "dispatch_center_id",
    sectionId: "core",
    label: "Dispatch center ID",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "dispatch_location_address",
    sectionId: "core",
    label: "Dispatch location",
    inputKind: "text",
    required: true,
    layout: "full",
  },
  {
    id: "incident_location_address",
    sectionId: "core",
    label: "Incident location",
    inputKind: "text",
    required: true,
    layout: "full",
  },
  {
    id: "initial_dispatch_code",
    sectionId: "core",
    label: "Initial dispatch code (incident code)",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "dispatch_determinate_code",
    sectionId: "core",
    label: "Determinate dispatch code",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "dispatch_final_disposition",
    sectionId: "core",
    label: "Final disposition",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "incident_has_aid",
    sectionId: "core",
    label: "Was aid given or received?",
    inputKind: "select",
    optionsKey: "yes_no",
    layout: "half",
  },
  {
    id: "incident_aid_agency_type",
    sectionId: "core",
    label: "Aid Type",
    inputKind: "select",
    optionsKey: "aid_agency_type",
    requiredIf: {
      fieldId: "incident_has_aid",
      operator: "equals",
      value: "YES",
    },
    layout: "half",
  },
  {
    id: "incident_aid_direction",
    sectionId: "core",
    label: "Aid direction",
    inputKind: "select",
    optionsKey: "aid_direction",
    requiredIf: {
      fieldId: "incident_aid_agency_type",
      operator: "equals",
      value: "FIRE_DEPARTMENT",
    },
    layout: "half",
  },
  {
    id: "incident_aid_type",
    sectionId: "core",
    label: "Aid type",
    inputKind: "select",
    optionsKey: "aid_type",
    requiredIf: {
      fieldId: "incident_aid_agency_type",
      operator: "equals",
      value: "FIRE_DEPARTMENT",
    },
    layout: "half",
  },
  {
    id: "incident_aid_department_name",
    sectionId: "core",
    label: "Aid department name(s)",
    inputKind: "select",
    optionsKey: "aid_department",
    requiredIf: {
      fieldId: "incident_aid_agency_type",
      operator: "equals",
      value: "FIRE_DEPARTMENT",
    },
    layout: "full",
  },
  {
    id: "incident_aid_nonfd",
    sectionId: "core",
    label: "Non FD Aid",
    inputKind: "multiselect",
    optionsKey: "aid_nonfd",
    requiredIf: {
      fieldId: "incident_aid_agency_type",
      operator: "equals",
      value: "NON_FD_AID",
    },
    layout: "full",
  },
  {
    id: "incident_people_present",
    sectionId: "core",
    label: "Were there people present?",
    inputKind: "select",
    optionsKey: "yes_no",
    required: true,
    layout: "half",
  },
  {
    id: "incident_displaced_number",
    sectionId: "core",
    label: "Number of people displaced",
    inputKind: "text",
    requiredIf: {
      fieldId: "incident_people_present",
      operator: "equals",
      value: "YES",
    },
    layout: "full",
  },
  {
    id: "incident_displaced_cause",
    sectionId: "core",
    label: "Displacement cause(s)",
    inputKind: "multiselect",
    optionsKey: "displace_cause_incident",
    layout: "half",
  },
  {
    id: "narrative_outcome",
    sectionId: "narrative",
    label: "Describe the final outcomes of the incident.",
    inputKind: "textarea",
    required: true,
    maxLength: 100000,
    rows: 7,
    layout: "full",
  },
  {
    id: "narrative_obstacles",
    sectionId: "narrative",
    label: "Describe any obstacles that impacted the incident.",
    inputKind: "textarea",
    maxLength: 100000,
    rows: 7,
    layout: "full",
  },
  {
    id: "location_place_type",
    sectionId: "location",
    label: "Place type",
    inputKind: "select",
    optionsKey: "location_place",
    layout: "half",
  },
  {
    id: "location_use_primary",
    sectionId: "location",
    label: "Primary location use",
    inputKind: "select",
    optionsKey: "location_use",
    layout: "half",
  },
  {
    id: "location_use_secondary",
    sectionId: "location",
    label: "Secondary location use",
    inputKind: "select",
    optionsKey: "location_use",
    layout: "half",
  },
  {
    id: "location_vacancy_cause",
    sectionId: "location",
    label: "Vacancy cause",
    inputKind: "select",
    optionsKey: "vacancy",
    layout: "half",
  },
  {
    id: "location_state",
    sectionId: "location",
    label: "State / Territory",
    inputKind: "select",
    optionsKey: "state",
    layout: "half",
  },
  {
    id: "location_country",
    sectionId: "location",
    label: "Country",
    inputKind: "select",
    optionsKey: "country",
    layout: "half",
  },
  {
    id: "location_direction_of_travel",
    sectionId: "location",
    label: "Direction of travel",
    inputKind: "select",
    optionsKey: "location_direction",
    layout: "half",
  },
  {
    id: "location_cross_street_type",
    sectionId: "location",
    label: "Cross street type",
    inputKind: "select",
    optionsKey: "location_cross_street",
    layout: "half",
  },
  {
    id: "location_postal_code",
    sectionId: "location",
    label: "Postal code",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "location_county",
    sectionId: "location",
    label: "County",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "incident_time_call_create",
    sectionId: "incidentTimes",
    label: "Call created time",
    inputKind: "datetime",
    layout: "half",
  },
  {
    id: "incident_time_call_answered",
    sectionId: "incidentTimes",
    label: "Call answered time",
    inputKind: "datetime",
    layout: "half",
  },
  {
    id: "incident_time_call_arrival",
    sectionId: "incidentTimes",
    label: "Call arrival time",
    inputKind: "datetime",
    layout: "half",
  },
  {
    id: "incident_time_unit_dispatched",
    sectionId: "incidentTimes",
    label: "Unit dispatched time",
    inputKind: "datetime",
    layout: "half",
  },
  {
    id: "incident_time_unit_enroute",
    sectionId: "incidentTimes",
    label: "Unit enroute time",
    inputKind: "datetime",
    layout: "half",
  },
  {
    id: "incident_time_unit_on_scene",
    sectionId: "incidentTimes",
    label: "Unit on-scene time",
    inputKind: "datetime",
    layout: "half",
  },
  {
    id: "incident_time_unit_clear",
    sectionId: "incidentTimes",
    label: "Unit clear time",
    inputKind: "datetime",
    layout: "half",
  },
  {
    id: "incident_time_clear",
    sectionId: "incidentTimes",
    label: "Incident clear time",
    inputKind: "datetime",
    layout: "half",
  },
  {
    id: "resource_primary_unit_id",
    sectionId: "resources",
    label: "Primary responding unit ID",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "resource_primary_unit_type",
    sectionId: "resources",
    label: "Primary unit type",
    inputKind: "select",
    optionsKey: "unit_type",
    layout: "half",
  },
  {
    id: "resource_primary_unit_staffing",
    sectionId: "resources",
    label: "Primary unit staffing",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "resource_primary_unit_response_mode",
    sectionId: "resources",
    label: "Primary unit response mode",
    inputKind: "select",
    optionsKey: "response_mode",
    layout: "half",
  },
  {
    id: "resource_additional_units",
    sectionId: "resources",
    label: "Additional responding units",
    inputKind: "textarea",
    rows: 4,
    placeholder: "Optional unit IDs or names (one per line).",
    layout: "full",
  },
  {
    id: "emerg_haz_disposition",
    sectionId: "hazards",
    label: "Hazard disposition",
    inputKind: "select",
    optionsKey: "hazard_disposition",
    layout: "half",
  },
  {
    id: "emerg_haz_evacuated_count",
    sectionId: "hazards",
    label: "Evacuated occupants/businesses",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "emerg_haz_chemical_name",
    sectionId: "hazards",
    label: "Chemical name",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "emerg_haz_chemical_dot",
    sectionId: "hazards",
    label: "DOT hazard class",
    inputKind: "select",
    optionsKey: "hazard_dot",
    layout: "half",
  },
  {
    id: "emerg_haz_chemical_unit",
    sectionId: "hazards",
    label: "Chemical quantity unit",
    inputKind: "select",
    optionsKey: "hazard_unit",
    layout: "half",
  },
  {
    id: "emerg_haz_chemical_source_target",
    sectionId: "hazards",
    label: "Chemical source/target",
    inputKind: "select",
    optionsKey: "source_target",
    layout: "half",
  },
  {
    id: "emerg_haz_electric_type",
    sectionId: "emergingHazards",
    label: "Electrical hazard type",
    inputKind: "select",
    optionsKey: "emerg_haz_elec",
    layout: "full",
  },
  {
    id: "emerg_haz_pv_type",
    sectionId: "emergingHazards",
    label: "Photovoltaic hazard type",
    inputKind: "select",
    optionsKey: "emerg_haz_pv",
    layout: "half",
  },
  {
    id: "emerg_haz_pv_source_target",
    sectionId: "emergingHazards",
    label: "PV source/target",
    inputKind: "select",
    optionsKey: "emerg_haz_pv_ign",
    layout: "half",
  },
  {
    id: "emerg_haz_suppression_methods",
    sectionId: "emergingHazards",
    label: "Emerging hazard suppression method(s)",
    inputKind: "multiselect",
    optionsKey: "emerg_haz_suppression",
    layout: "full",
  },
  {
    id: "fire_water_supply",
    sectionId: "fire",
    label: "Water supply",
    inputKind: "select",
    optionsKey: "fire_water_supply",
    layout: "half",
  },
  {
    id: "fire_investigation_needed",
    sectionId: "fire",
    label: "Investigation needed",
    inputKind: "select",
    optionsKey: "fire_invest_need",
    layout: "half",
  },
  {
    id: "fire_investigation_types",
    sectionId: "fire",
    label: "Investigation type(s)",
    inputKind: "multiselect",
    optionsKey: "fire_invest_types",
    layout: "full",
  },
  {
    id: "fire_suppression_appliances",
    sectionId: "fire",
    label: "Suppression appliance(s)",
    inputKind: "multiselect",
    optionsKey: "fire_suppression_appliance",
    layout: "full",
  },
  {
    id: "fire_condition_on_arrival",
    sectionId: "fire",
    label: "Fire condition on arrival",
    inputKind: "select",
    optionsKey: "fire_condition_arrival",
    layout: "half",
  },
  {
    id: "fire_cause_in_structure",
    sectionId: "fire",
    label: "Fire cause (inside structure)",
    inputKind: "select",
    optionsKey: "fire_cause_in",
    layout: "half",
  },
  {
    id: "fire_cause_outside",
    sectionId: "fire",
    label: "Fire cause (outside)",
    inputKind: "select",
    optionsKey: "fire_cause_out",
    layout: "half",
  },
  {
    id: "fire_burn_extent",
    sectionId: "fire",
    label: "Extent",
    inputKind: "select",
    optionsKey: "full_partial",
    layout: "half",
  },
  {
    id: "fire_smoke_alarm_types",
    sectionId: "fire",
    label: "Smoke alarm type(s)",
    inputKind: "multiselect",
    optionsKey: "alarm_smoke",
    layout: "half",
  },
  {
    id: "fire_smoke_alarm_operation",
    sectionId: "fire",
    label: "Smoke alarm operation",
    inputKind: "select",
    optionsKey: "alarm_operation",
    layout: "half",
  },
  {
    id: "fire_smoke_alarm_failure",
    sectionId: "fire",
    label: "Smoke alarm failure reason",
    inputKind: "select",
    optionsKey: "alarm_failure",
    layout: "half",
  },
  {
    id: "fire_alarm_types",
    sectionId: "fire",
    label: "Fire alarm type(s)",
    inputKind: "multiselect",
    optionsKey: "alarm_fire",
    layout: "half",
  },
  {
    id: "fire_other_alarm_types",
    sectionId: "fire",
    label: "Other alarm type(s)",
    inputKind: "multiselect",
    optionsKey: "alarm_other",
    layout: "half",
  },
  {
    id: "fire_suppression_types",
    sectionId: "fire",
    label: "Fire suppression system type(s)",
    inputKind: "multiselect",
    optionsKey: "suppress_fire",
    layout: "half",
  },
  {
    id: "fire_suppression_operation",
    sectionId: "fire",
    label: "Fire suppression operation",
    inputKind: "select",
    optionsKey: "suppress_operation",
    layout: "half",
  },
  {
    id: "fire_suppression_no_operation",
    sectionId: "fire",
    label: "No-operation cause(s)",
    inputKind: "multiselect",
    optionsKey: "suppress_no_operation",
    layout: "half",
  },
  {
    id: "fire_cooking_suppression",
    sectionId: "fire",
    label: "Cooking suppression system(s)",
    inputKind: "multiselect",
    optionsKey: "suppress_cooking",
    layout: "half",
  },
  {
    id: "fire_suppression_time",
    sectionId: "fire",
    label: "Suppression timing",
    inputKind: "select",
    optionsKey: "suppress_time",
    layout: "half",
  },
  {
    id: "exposure_location_detail",
    sectionId: "exposures",
    label: "Exposure location detail",
    inputKind: "select",
    optionsKey: "exposure_location_detail",
    layout: "half",
  },
  {
    id: "exposure_item_type",
    sectionId: "exposures",
    label: "Exposure item type",
    inputKind: "select",
    optionsKey: "exposure_item",
    layout: "half",
  },
  {
    id: "exposure_damage_type",
    sectionId: "exposures",
    label: "Exposure damage type",
    inputKind: "select",
    optionsKey: "exposure_damage",
    layout: "half",
  },
  {
    id: "exposure_displacement_count",
    sectionId: "exposures",
    label: "Exposure displacement count",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "exposure_displacement_causes",
    sectionId: "exposures",
    label: "Exposure displacement cause(s)",
    inputKind: "multiselect",
    optionsKey: "displace_cause_exposure",
    layout: "full",
  },
  {
    id: "exposure_people_present",
    sectionId: "exposures",
    label: "People present at exposure",
    inputKind: "select",
    optionsKey: "yes_no_unknown",
    layout: "half",
  },
  {
    id: "risk_reduction_completed",
    sectionId: "riskReduction",
    label: "Risk reduction completed",
    inputKind: "select",
    optionsKey: "yes_no_unknown",
    layout: "half",
  },
  {
    id: "risk_reduction_follow_up_required",
    sectionId: "riskReduction",
    label: "Follow-up required",
    inputKind: "select",
    optionsKey: "yes_no_unknown",
    layout: "half",
  },
  {
    id: "risk_reduction_referrals",
    sectionId: "riskReduction",
    label: "Referrals made",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "risk_reduction_contacts_made",
    sectionId: "riskReduction",
    label: "Contacts made",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "medical_patient_care_evaluation",
    sectionId: "medical",
    label: "Patient care evaluation",
    inputKind: "select",
    optionsKey: "medical_patient_care",
    layout: "half",
  },
  {
    id: "medical_patient_status",
    sectionId: "medical",
    label: "Patient status",
    inputKind: "select",
    optionsKey: "medical_patient_status",
    layout: "half",
  },
  {
    id: "medical_transport_disposition",
    sectionId: "medical",
    label: "Transport disposition",
    inputKind: "select",
    optionsKey: "medical_transport",
    layout: "half",
  },
  {
    id: "medical_patient_care_report_id",
    sectionId: "medical",
    label: "Patient care report ID",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "medical_patient_count",
    sectionId: "medical",
    label: "Patient count",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "casualty_type",
    sectionId: "rescuesCasualties",
    label: "Casualty type",
    inputKind: "select",
    optionsKey: "casualty_type",
    layout: "half",
  },
  {
    id: "casualty_cause",
    sectionId: "rescuesCasualties",
    label: "Casualty cause",
    inputKind: "select",
    optionsKey: "casualty_cause",
    layout: "half",
  },
  {
    id: "casualty_gender",
    sectionId: "rescuesCasualties",
    label: "Casualty gender",
    inputKind: "select",
    optionsKey: "gender",
    layout: "half",
  },
  {
    id: "casualty_race",
    sectionId: "rescuesCasualties",
    label: "Casualty race",
    inputKind: "select",
    optionsKey: "race",
    layout: "half",
  },
  {
    id: "casualty_ppe",
    sectionId: "rescuesCasualties",
    label: "Firefighter PPE involved",
    inputKind: "multiselect",
    optionsKey: "casualty_ppe",
    layout: "full",
  },
  {
    id: "rescue_type",
    sectionId: "rescuesCasualties",
    label: "Rescue type",
    inputKind: "select",
    optionsKey: "rescue_type",
    layout: "half",
  },
  {
    id: "rescue_actions",
    sectionId: "rescuesCasualties",
    label: "Rescue action(s)",
    inputKind: "multiselect",
    optionsKey: "rescue_action",
    layout: "half",
  },
  {
    id: "rescue_impediments",
    sectionId: "rescuesCasualties",
    label: "Rescue impediment(s)",
    inputKind: "multiselect",
    optionsKey: "rescue_impediment",
    layout: "half",
  },
  {
    id: "rescue_presence_known",
    sectionId: "rescuesCasualties",
    label: "Presence known",
    inputKind: "select",
    optionsKey: "rescue_presence_known",
    layout: "half",
  },
  {
    id: "rescue_mode",
    sectionId: "rescuesCasualties",
    label: "Rescue mode",
    inputKind: "select",
    optionsKey: "rescue_mode",
    layout: "half",
  },
  {
    id: "rescue_path",
    sectionId: "rescuesCasualties",
    label: "Rescue path",
    inputKind: "select",
    optionsKey: "rescue_path",
    layout: "half",
  },
  {
    id: "rescue_elevation",
    sectionId: "rescuesCasualties",
    label: "Rescue elevation",
    inputKind: "select",
    optionsKey: "rescue_elevation",
    layout: "half",
  },
  {
    id: "attachment_label",
    sectionId: "attachments",
    label: "Attachment label",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "attachment_url",
    sectionId: "attachments",
    label: "Attachment URL",
    inputKind: "text",
    layout: "half",
  },
  {
    id: "attachment_notes",
    sectionId: "attachments",
    label: "Attachment notes",
    inputKind: "textarea",
    rows: 5,
    layout: "full",
  },
  ...NERIS_SECTION_NOTE_FIELDS,
];

export function getNerisValueOptions(
  key: keyof typeof NERIS_VALUE_SETS,
): NerisValueOption[] {
  return [...NERIS_VALUE_SETS[key]];
}

export function getNerisFieldsForSection(sectionId: NerisSectionId): NerisFieldMetadata[] {
  return NERIS_FORM_FIELDS.filter((field) => field.sectionId === sectionId);
}

function evaluateNerisRule(rule: NerisConditionalRule, values: NerisFormValues): boolean {
  const value = (values[rule.fieldId] ?? "").trim();
  const expectedValue = rule.value ? toApiEnumValue(rule.value) : "";
  if (rule.operator === "notEmpty") {
    return value.length > 0;
  }
  if (rule.operator === "isEmpty") {
    return value.length === 0;
  }
  if (rule.operator === "includes") {
    return value
      .split(",")
      .map((item) => item.trim())
      .filter((item) => item.length > 0)
      .map((item) => toApiEnumValue(item))
      .includes(expectedValue);
  }
  return toApiEnumValue(value) === expectedValue;
}

export function isNerisFieldRequired(
  field: NerisFieldMetadata,
  values: NerisFormValues,
): boolean {
  if (field.required) {
    return true;
  }
  if (!field.requiredIf) {
    return false;
  }
  return evaluateNerisRule(field.requiredIf, values);
}

export function validateNerisSection(
  sectionId: NerisSectionId,
  values: NerisFormValues,
): NerisValidationResult {
  const sectionFields = getNerisFieldsForSection(sectionId);
  const errors: Record<string, string> = {};

  for (const field of sectionFields) {
    const value = (values[field.id] ?? "").trim();
    const isRequired = isNerisFieldRequired(field, values);
    if (isRequired && !value) {
      errors[field.id] = `${field.label} is required.`;
      continue;
    }

    if (field.maxLength && value.length > field.maxLength) {
      errors[field.id] = `${field.label} must be ${field.maxLength} characters or less.`;
      continue;
    }

    if (field.optionsKey && value) {
      const allowedValues = new Set<string>(
        NERIS_VALUE_SETS[field.optionsKey].map((option) => option.value),
      );
      if (field.inputKind === "multiselect") {
        const invalidSelections = value
          .split(",")
          .map((entry) => entry.trim())
          .filter((entry) => entry.length > 0)
          .map((entry) => toApiEnumValue(entry))
          .filter((entry) => !allowedValues.has(entry));
        if (invalidSelections.length) {
          errors[field.id] = `${field.label} contains one or more invalid selections.`;
        }
      } else if (!allowedValues.has(toApiEnumValue(value))) {
        errors[field.id] = `${field.label} must use an allowed value.`;
      }
    }
  }

  if (sectionId === "core") {
    const displacedNumber = (values.incident_displaced_number ?? "").trim();
    if (displacedNumber && !/^\d+$/.test(displacedNumber)) {
      errors.incident_displaced_number = "Number of people displaced must be a whole number.";
    }

    const additionalIncidentTypes = (values.additional_incident_types ?? "")
      .split(",")
      .map((entry) => entry.trim())
      .filter((entry) => entry.length > 0);
    if (additionalIncidentTypes.length > 2) {
      errors.additional_incident_types =
        "Additional incident types can include a maximum of 2 selections.";
    }

    const actions = (values.incident_actions_taken ?? "").trim();
    const noAction = (values.incident_noaction ?? "").trim();
    if (actions && noAction) {
      errors.incident_actions_taken =
        "Use either Actions taken or No action reason, not both.";
      errors.incident_noaction =
        "Use either No action reason or Actions taken, not both.";
    }
  }

  return {
    isValid: Object.keys(errors).length === 0,
    errors,
  };
}

function normalizeNerisTime(receivedAt: string | undefined): string {
  if (!receivedAt) {
    return "15:30:13";
  }
  const match = receivedAt.match(/^(\d{2}:\d{2}:\d{2})$/);
  if (!match) {
    return "15:30:13";
  }
  return match[1];
}

function toDateTimeLocal(value: string | undefined, fallback: string): string {
  if (!value) {
    return fallback;
  }
  const timeMatch = value.match(/^(\d{2}:\d{2}:\d{2})$/);
  if (timeMatch) {
    return `2026-02-18T${timeMatch[1]}`;
  }
  return fallback;
}

function extractAddressCode(segment: string | undefined): string {
  if (!segment) {
    return "";
  }
  const matches = segment.toUpperCase().match(/\b[A-Z]{2}\b/g);
  return matches?.[matches.length - 1] ?? "";
}

function inferLocationStateAndCountry(address: string | undefined): {
  locationState: string;
  locationCountry: string;
} {
  const fallbackCountry = "US";
  if (!address) {
    return {
      locationState: "",
      locationCountry: fallbackCountry,
    };
  }

  const segments = address
    .split(",")
    .map((segment) => segment.trim())
    .filter((segment) => segment.length > 0);
  const stateOptionValues = new Set<string>(NERIS_VALUE_SETS.state.map((option) => option.value));
  const countryOptionValues = new Set<string>(
    NERIS_VALUE_SETS.country.map((option) => option.value),
  );
  const lastSegment = segments[segments.length - 1] ?? "";
  const stateSegment = segments.length >= 4 ? (segments[segments.length - 2] ?? "") : lastSegment;
  const countrySegment = segments.length >= 4 ? lastSegment : "";
  const normalizedCountrySegment = countrySegment.trim().toUpperCase();
  const countryCodeFromAddress =
    normalizedCountrySegment === "USA" || normalizedCountrySegment === "UNITED STATES"
      ? "US"
      : extractAddressCode(countrySegment);
  const stateCodeFromAddress = extractAddressCode(stateSegment);

  return {
    locationState: stateOptionValues.has(stateCodeFromAddress) ? stateCodeFromAddress : "",
    locationCountry: countryOptionValues.has(countryCodeFromAddress)
      ? countryCodeFromAddress
      : fallbackCountry,
  };
}

export function createDefaultNerisFormValues({
  callNumber,
  receivedAt,
  address,
}: CreateNerisDefaultsInput): NerisFormValues {
  const dispatchDateTime = toDateTimeLocal(receivedAt, "2026-02-18T15:30:13");
  const { locationState, locationCountry } = inferLocationStateAndCountry(address);

  return {
    incident_neris_id: `NERIS-${callNumber.replace(/[^A-Z0-9]/gi, "")}`,
    incident_internal_id: callNumber,
    incident_onset_date: "2026-02-18",
    incident_onset_time: normalizeNerisTime(receivedAt),
    dispatch_internal_id: callNumber.replace(/^D-/, ""),
    primary_incident_type: "",
    additional_incident_types: "",
    special_incident_modifiers: "",
    incident_actions_taken: "",
    incident_noaction: "",
    fd_neris_id: "",
    dispatch_center_id: "0000",
    dispatch_location_address: address ?? "",
    incident_location_address: address ?? "",
    location_state: locationState,
    location_country: locationCountry,
    initial_dispatch_code: "AMB.UNRESP-BREATHING",
    dispatch_determinate_code: "",
    dispatch_final_disposition: "",
    dispatch_automatic_alarm: "",
    incident_people_present: "",
    incident_time_call_create: dispatchDateTime,
    incident_time_call_answered: dispatchDateTime,
    incident_time_call_arrival: dispatchDateTime,
    time_incident_clear: "",
    incident_displaced_number: "",
    incident_displaced_cause: "",
    incident_has_aid: "",
    incident_aid_agency_type: "",
    incident_aid_direction: "",
    incident_aid_type: "",
    incident_aid_department_name: "",
    incident_aid_nonfd: "",
    narrative_outcome: "",
    narrative_obstacles: "",
    location_notes: "",
    incidentTimes_notes: "",
    resources_notes: "",
    emergingHazards_notes: "",
    hazards_notes: "",
    fire_notes: "",
    exposures_notes: "",
    riskReduction_notes: "",
    medical_notes: "",
    rescuesCasualties_notes: "",
    attachments_notes: "",
  };
}
